- src/components/common/Header.tsx
- src/components/common/HeaderButton.tsx
- src/components/icons/BackIcon.tsx
- src/components/icons/EditIcon.tsx
- src/components/icons/ShareIcon.tsx
- src/components/icons/TrashIcon.tsx
> [Feat] Header 공통 컴포넌트 생성

- src/components/common/Accordion.tsx
- src/constants/accordionData.tsx
> [Feat] 공통 컴포넌트 Accordion 구현

- src/App.tsx
- src/components/ImageUpload.tsx
- src/components/useImageStore.tsx
> [Feat] 대표이미지 업로드 컴포넌트 생성

- src/components/wedding/Calendar.tsx
- src/components/wedding/CalendarSection.tsx
- src/components/wedding/DDay.tsx
- src/components/wedding/DatePicker.tsx
- src/components/wedding/TimePicker.tsx
- src/components/wedding/WeddingDateInput.tsx
- src/utils/dateUtils.ts
> [Feat] 예식 일시 입력, 캘린더, 디데이 컴포넌트

- package-lock.json
- package.json
- src/App.tsx
- src/components/ContactInput.tsx
- src/components/useContactStore.tsx
> [Feat] 사용자 연락처 입력 컴포넌트 생성

- package-lock.json
- package.json
- src/components/common/DaumPost.tsx
- src/components/common/InputAddress.tsx
- src/components/common/StepNavigation.tsx
- src/components/common/Stepper.tsx
> [Feat] 공통 컴포넌트 Stepper, StepNavigation 구현

- src/components/display/ContactSection/CallButton.tsx
- src/components/display/ContactSection/Contact.tsx
- src/components/display/ContactSection/ContactSection.tsx
- src/components/display/ContactSection/ContactTitle.tsx
- src/components/icons/PhoneIcon.tsx
- 전화기 아이콘 누르면 바로 전화걸 수 있게 구현했습니다
> [Feat] 연락처 UI 구현

- src/components/display/CalendarSection/Calendar.tsx
- src/components/display/CalendarSection/CalendarSection.tsx
- src/components/display/CalendarSection/CalendarTitle.tsx
- src/components/display/CalendarSection/DDay.tsx
> [Design] 캘린더 UI 수정

- src/components/display/ResultDisplay.tsx
- src/pages/PreviewInvitaionPage.tsx
- src/styles/global.css
- tailwind.config.js
-  미리보기, 결과물 레이아웃 설정하고 만든 UI 넣었는데 잘 나오는 것 같습니다
> [Feat] 미리보기 페이지 구현 및 스타일 정의

- package-lock.json
- src/components/display/ThumbnailSection/BrideGroomName.tsx
- src/components/display/ThumbnailSection/DateTitle.tsx
- src/components/display/ThumbnailSection/Image.tsx
- src/components/display/ThumbnailSection/ThumbnailSection.tsx
> [Feat] ThumbnailSection

- src/components/common/Card/CreateCard.tsx
- src/components/common/Modal/InputTitleModal.tsx
- src/components/common/Modal/ReusableModal.tsx
- src/pages/CreateInvitationPage.tsx
- src/pages/DashBoardPage.tsx
- src/store/useInvitaionStore.ts
> [Feat] 모달창 구현

- src/App.tsx
- src/components/ResetPassword/ResetPasswordButton.tsx
- src/components/ResetPassword/ResetPasswordForm.tsx
- src/components/ResetPassword/TemporaryPasswordModal.tsx
- src/pages/ResetPasswordPage.tsx
- src/services/userService.ts
- src/utils/config.ts
API 요청 후 입력한 이메일로 임시 비밀번호 발급되고 임시 비밀번호로 로그인 가능합니다. 
> [Feat] 비밀번호 재설정 기능 구현

- src/components/display/GreetingSection/FamilyName.tsx
- src/components/display/GreetingSection/GreetingSection.tsx
- src/components/display/ThumbnailSection/WeddingInformation.tsx
- ThumbnailSection: 예식장명, 층과 홀 default 값 추가
- GreetingSection/FamilyName: 이름이 모두 입력됐을 때 렌더링되도록 수정
> [Feat] 완성본

- src/components/display/AttendanceSection/AttendanceSection.tsx
> fix : build error

- src/components/common/Header/Header.tsx
- src/components/common/PhotoTalk/PhotoTalkCard.tsx
- src/components/common/PhotoTalk/PhotoTalkEditor.tsx
- src/components/common/PhotoTalk/PhotoTalkGallery.tsx
- src/components/common/PhotoTalk/PhotoTalkList.tsx
- src/components/display/AttendanceSection/AttendanceSection.tsx
- src/components/form/BasicInformation/AddressInput/AddressInput.tsx
- src/pages/EditInvitationPage.tsx
- src/pages/MyPage.tsx
- src/pages/PhotoTalk/AdminPhotoTalkPage.tsx
- src/pages/PhotoTalk/PhotoTalkPage.tsx
> [Design] 최종 디자인 수정

- src/App.tsx
- src/components/common/Card/CardHeader.tsx
- src/components/common/PhotoTalk/PasswordConfirmModal.tsx
- src/components/common/ToastPopup.tsx
- src/components/display/AccountSection/AccountSection.tsx
- src/components/display/AttendanceSection/AttendanceSection.tsx
- src/components/display/CalendarSection/CalendarSection.tsx
- src/components/display/ContactSection/ContactSection.tsx
- src/components/display/GallerySection/GallerySection.tsx
- src/components/display/GreetingSection/FamilyName.tsx
- src/components/display/GreetingSection/GreetingSection.tsx
- src/components/display/LocationSection/LocationSection.tsx
- src/components/display/LocationSection/Map.tsx
- src/components/display/PhotoTalkSection/PhotoTalkSection.tsx
- src/components/display/ThumbnailSection/WeddingInformation.tsx
- src/components/form/Theme/FontFeature/FontFeature.tsx
- src/components/login/EmailLogin/EmailLoginButton.tsx
- src/components/login/Login.tsx
- src/components/login/SocialLogin/KakaoLoginButton.tsx
- src/components/login/SocialLogin/NaverLoginButton.tsx
- src/pages/PhotoTalk/PhotoTalkPage.tsx
> fix:Overall Style fix

- src/components/common/PhotoTalk/List/PhotoTalkCommonList.tsx
- src/components/common/PhotoTalk/List/PhotoTalkListAdmin.tsx
- src/components/common/PhotoTalk/List/PhotoTalkListGuest.tsx
- src/components/common/Skeleton/SkeletonCard.tsx
- src/components/common/Skeleton/SkeletonGallery.tsx
- src/components/common/Skeleton/SkeletonPhotoTalk.tsx
- src/pages/DashBoardPage.tsx
> [Feat] 스켈레톤 UI 추가

- src/components/common/PhotoTalk/Editor/PhotoTalkEditor.tsx
- src/components/common/PhotoTalk/List/PhotoTalkListAdmin.tsx
- src/components/common/PhotoTalk/List/PhotoTalkListGuest.tsx
- src/components/common/PhotoTalk/Modal/PasswordConfirmModal.tsx
- src/components/icons/CloseIcon.tsx
- src/components/icons/DownloadIcon.tsx
- src/hooks/usePhototalk.tsx
- src/hooks/usePhototalkAction.tsx
- src/pages/PhotoTalk/AdminPhotoTalkPage.tsx
- src/pages/PhotoTalk/GuestPhotoTalkPage.tsx
- src/utils/downloadUtils.ts
> [Fix] 포토톡 비밀번호 확인 & 무한스크롤 refetch

- src/components/common/PhotoTalk/Editor/PhotoTalkEditor.tsx
> [FIX] refetch 함수

- package-lock.json
- src/actions/invitationAction.ts
- src/components/common/CreateInvitation/PreviewButton.tsx
- src/components/display/ThumbnailSection/DateTitle.tsx
- src/store/useWeddingStore.ts
#151 
- Date 포멧 수정 
-  Preview URL userID 추가 
- wedding date NaN 예외처리 추가 
> NaN  으로 표시되는 에러 수정 및 preview URL에 userId 추가 
> [Fix] invitation response detail
